name: kubeconfig
version: 0.1.0.0
description: |
  This package contains functions for working with kubeconfig files.

  Usage of kubeconfig files are described at https://kubernetes.io/docs/concepts/configuration/organize-cluster-access-kubeconfig/
library:
  source-dirs: src
tests:
  spec:
    main: Spec.hs
    source-dirs: test
    dependencies:
      - hspec
      - yaml
      - kubeconfig
extra-source-files:
  - test/testdata/*
dependencies:
  - base >=4.7 && <5.0
  - aeson
  - containers
  - text
